package algorithm.leetcode.algorithm;
/*
 * easy
 * 389. Find the Difference
 *  Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 */
public class NO389_FindtheDifference {
    public char findTheDifference(String s, String t) {
        if(s == null || s.length() == 0){
            return t.charAt(0);
        }
        int[] c = new int[26];
        for(int i = 0 ; i < s.length() ; i++){
            c[s.charAt(i)-'a']++;
        }
        for(int i = 0 ; i < t.length() ; i++){
            if(c[t.charAt(i)-'a'] == 0){
                return t.charAt(i);
            }
            c[t.charAt(i)-'a']--;
        }
        return 0;
    }
	public char findTheDifference2(String s, String t) {
		char c = 0;
		for (int i = 0; i < s.length(); ++i) {
			c ^= s.charAt(i);
		}
		for (int i = 0; i < t.length(); ++i) {
			c ^= t.charAt(i);
		}
		return c;
	}
}
